scenario_generation:
  experiment_name: "aurora_ferry_test_scenario_batch"
  description: "Scenario sampling configuration based on odm_training.json"
  seed: 42
  number_of_scenarios: 1000

  simulation:
    duration_sec: 800
    dt: 0.2

  guidance: 
    update_every_sec: 30
    lookahead_distance: 1500.0
    colregs: True
    good_seamanship: True
    abort_colregs_after_iter: 1
    buffer_target_ships: 100.0
    term_dist: 500.0
    dchi: 10.0
    du: 0.5
    delay: 20
    delay_type: 'symmetric'
    corridor_width: 50
    simplify_corridor: 1

  navigation:
    q_tt: [0.1, 0.1, 0.001, 0.0003]
    r_ais: [10, 10, 0.04, 0.00122]
    r_camera: [0.00008, 640000]

  control:
    path_to_weights: 'models/sac/2026_05_22_15_10_57'
    algorithm: 'sac'

  ais_data_paths:
    - "data/raw/2023_04_06.csv"
    - "data/raw/2023_04_15.csv"

  mmsi_to_exclude: [265041000]

  start:
    Helsingor: [[6212200, 6212700], [351600, 351900]] # 6212309, 351458
    Helsingborg: [[6212600, 6213300], [355700, 356000]] # 6213303, 356200
    info: "Each start position is associated with ranges for possible east-north values"


  operational_domain:
    ferry:
      target_speed:
        min: 5
        max: 7.5
        mean: 6.5
        std: 1
      mass: 2250000
      passengers:
        number:
          min: 10
          max: 1250
        mass:
          min: 63
          max: 93
          std: 5
          mean: 78
      cars:
        number:
          min: 0
          max: 240
        mass:
          min: 900
          max: 1500
          std: 100
          mean: 1200

    wind:
      angle:
        min: -3.14159
        max: 3.14159
        ornstein_uhlenbeck:
          attraction: 0.03
          amplitude: 0.05
      speed:
        min: 0.0
        max: 15.0
        ornstein_uhlenbeck:
          attraction: 0.03
          amplitude: 0.1
      info: "According to https://app.fcoo.dk/ifm-maps/denmark/, wind up to 15m/s in any direction"

    current:
      angle:
        min: -3.14159
        max: 3.14159
        ornstein_uhlenbeck:
          attraction: 0.01
          amplitude: 0.01
      speed:
        min: 0.0
        max: 1.0
        ornstein_uhlenbeck:
          attraction: 0.01
          amplitude: 0.1
      info: "According to https://app.fcoo.dk/ifm-maps/denmark/, current up to 2kn in both directions"

    illumination:
      min: 0.0
      max: 1.0

    visibility:
      min: 0.0
      max: 1.0

  sensors:
    states:
      noise_covariance:
        min:
          - 1e-3
          - 1e-3
          - 0.00035
          - 5e-3
          - 5e-3
          - 5e-3
          - 0.00314159
          - 0.00314159
          - 0.00314159
          - 0.00314159
        max:
          - 1e-2
          - 1e-2
          - 0.0035
          - 5e-2
          - 5e-2
          - 5e-2
          - 0.0314159
          - 0.0314159
          - 0.0314159
          - 0.0314159
    ais:
      enabled: True
      update_every_sec: 1
      noise_covariance:
        min:
          - 3.0
          - 3.0
          - 0.1
          - 0.005
        max:
          - 5.0
          - 5.0
          - 0.5
          - 0.015
        info: "measure states are N, E, SOG [kn], COG [rad]"
    camera:
      enabled: True
      update_every_sec: 1
      failure:
        prob: 0.0
        time: 
          min: 0
          max: 1
          mean: 0.3
          std: 0.1
      info: "probability of a camera blackout during an episode."

